### ISSUE TITLE
Doesn't work for not staged files

### ISSUE THREAD

**Issue by max-wittig** [max-wittig/smartsquash#1]
```sh
Fetching files changed by commits...
Traceback (most recent call last):
  File "/Users/max/.pyenv/versions/3.8.1/bin/sq", line 8, in <module>
    sys.exit(main())
  File "/Users/max/.pyenv/versions/3.8.1/lib/python3.8/site-packages/smartsquash/__main__.py", line 53, in main
    sq.fixup(target_branch, repo, dry)
  File "/Users/max/.pyenv/versions/3.8.1/lib/python3.8/site-packages/smartsquash/sq.py", line 44, in fixup
    run_fixup(repo, target_branch, closes_change_commit, add, dry)
  File "/Users/max/.pyenv/versions/3.8.1/lib/python3.8/site-packages/smartsquash/fixup.py", line 26, in run_fixup
    repo.git.commit(*command)
  File "/Users/max/.pyenv/versions/3.8.1/lib/python3.8/site-packages/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/max/.pyenv/versions/3.8.1/lib/python3.8/site-packages/git/cmd.py", line 1020, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/max/.pyenv/versions/3.8.1/lib/python3.8/site-packages/git/cmd.py", line 831, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git commit --fixup 67e18958f2501e7bfaa815bc3b3f181365c17818
  stdout: 'On branch refactor/gitleaks-upgrade
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   gitleaks.toml
```

**Comment by max-wittig** [comment]
Fixed
